version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js 20...
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - node -v
      - npm -v
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install

  build:
    commands:
      - echo Building frontend...
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync ./dist s3://testing-pipeline-in-nva

artifacts:
  files:
    - '**/*'
